language: node_js
node_js: 
  - "node"

before_script:
  - npm install -g gulp
script:
  - gulp build
  - cd ./public
  - git init
  - git config --global push.default matching
  - git config --global user.email "${GitHubEMail}"
  - git config --global user.name "${GitHubUser}"
  - git remote add origin https://${GitHubKEY}@github.com/${GitHubUser}/STFW.info.git
  - git branch build
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force --set-upstream origin build

cache:
  directories:
    - "node_modules"
